spring:
  config:
    activate:
      on-profile: dev
name: dev-YAML
environment: testing
enabled: true
servers:
  - http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - http://localhost:8080


