spring:
  config:
    activate:
      on-profile: dev
name: dev-YAML
environment: testing
enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true

