spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root:
      http://localhost:8080: INFO
name: dev-YAML
environment: testing
enabled: true
servers:
  - http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root:
      http://localhost:8080: DEBUG
name: prod-YAML
environment: production
enabled: true
servers:
  - http://localhost:8080


