
INSERT INTO QUESTIONS (QUESTION,ANSWER) VALUES ('question1', false);
INSERT INTO QUESTIONS (QUESTION,ANSWER) VALUES ('question2', false);
INSERT INTO QUESTIONS (QUESTION,ANSWER) VALUES ('question3', true);
INSERT INTO QUESTIONS (QUESTION,ANSWER) VALUES ('question4', false);
